use_frameworks!

target 'MVCacher_Example' do
  pod 'MVCacher', :path => '../'
  
  pod 'AAExtensions'
  pod 'AAViewAnimator'
  pod 'AAMaterialSpinner'
  pod 'AANetworking'
  

  target 'MVCacher_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
